### ISSUE TITLE
Refreshing the page highlights the Commits tab as active

### ISSUE THREAD

**Issue by russellbanks** [NirmalScaria/le-git-graph#22]
Refreshing the page reloads the Commits tab highlighted, as if it is the currently selected tab. This was tested on Firefox:
![firefox_mhF4zKAr5M](https://user-images.githubusercontent.com/74878137/203778034-f43889f7-2a82-4033-8fe6-00a37ae7b8ee.gif)

**Comment by russellbanks** [comment]
This seems to only be present if the page is refreshed while the Issues tab is selected. It doesn't seem to be present with any other tab.

**Comment by NirmalScaria** [comment]
Great find! I was aware there were bugs with the commits button selection logic, but didn't know how and what cases exactly. Will try fixing this soon. 😄

**Comment by NirmalScaria** [comment]
This has been fixed. Will be out with the next version release.
