### ISSUE TITLE
Very high CPU and RAM usage when loading old commits

### ISSUE THREAD

**Issue by carun** [NirmalScaria/le-git-graph#3]
![image](https://user-images.githubusercontent.com/471374/196275284-082c03f6-f51a-447f-bb6f-f1230a74a2a1.png)

**Comment by NirmalScaria** [comment]
The commit should add considerable performance improvement in the overall workflow of the extension. And I believe it could be further improved by using a web worker as suggested by  @BitBlitObviMormon in issue #34 . I will start working on it soon. Sorry for taking this long for this fix.
