### ISSUE TITLE
Access private repos without write access

### ISSUE THREAD

**Issue by probablykasper** [NirmalScaria/le-git-graph#53]
**Is your feature request related to a problem? Please describe.**
I'd like to use this extension with private org repos, but I don't really trust giving write access.

**Describe the solution you'd like**
Improved OAuth to support organizations, or support for fine-grained PATs

**Describe alternatives you've considered**
None

**Comment by NirmalScaria** [comment]
1. OAuth doesn't support a "read-only" access level to repos. Its either "repo" access level, or no access to repos at all. Hence, there is no way to change it with OAuth unless GitHub makes support for that option.
.
2. At the time of developing the extension, Github GraphQL API (which the extension completely relies upon) had no support for fine grained tokens.
But now it seems it is supported. And it works out of the box, with no modifications to the extension. You could choose "Custom PAT" option in the extension authentication page and enter the fine grained token there. It works.
.
The permission required is "Read-only" on "contents" option of the repositories it is meant to be used on. (It can be specified while generating the fine grained token.)

**Comment by probablykasper** [comment]
Looks like the organization needs to explicitly allow access for fine-grained PATs. Weird situation
<img width="364" alt="image" src="https://github.com/NirmalScaria/le-git-graph/assets/11315492/0aab203b-9c8b-4c04-894c-15d203a67f39">

<img width="602" alt="image" src="https://github.com/NirmalScaria/le-git-graph/assets/11315492/aad3c262-b24d-438c-bee2-742725945e97">
