### ISSUE TITLE
It itsn't working. Domain changed?

### ISSUE THREAD

**Issue by usarral** [NirmalScaria/le-git-graph#74]
**Describe the bug**
It cant be authorized becouse throws 404 after github authorize
**To Reproduce**

**Expected behavior**
Authorize OK
**Screenshots**

**Version information:**
 - OS: Linux
 - Browser  brave
 - Version 1.2.8
 - Repository where this issue was observed https://www.github.com/NirmalScaria/commitTest

**Comment by SonGokussj4** [comment]
Same problem here. Wanted to try this extension and not working :-)

**Comment by NirmalScaria** [comment]
Hey, thank you for reporting.
Yes, there was a problem with the deployment. It must have been fixed now. Feel free to reopen if the issue persists.

**Comment by usarral** [comment]
It continue failing

**Comment by usarral** [comment]
Now throws connection clossed
