### ISSUE TITLE
Graph node misaligned with commit list item.

### ISSUE THREAD

**Issue by Eyre-S** [NirmalScaria/le-git-graph#76]
**Describe the bug**
The height between two graph nodes is slightly smaller than the list item's height, as a result the graph will misaligned with the list after some pages.

**To Reproduce**
1. Go to Commits tag in this repository.
2. Load some more pages.
3. See the misaligned.

**Expected behavior**

The graph will always align to the tree.

**Screenshots**

![image](https://github.com/NirmalScaria/le-git-graph/assets/31265413/4dbcc94a-d02c-428a-a45a-abb4984446da)

**Version information:**
 - OS: Windows 11 Pro build 22631.3527
 - Browser: Edge 124.0.2478.105
 - Version: 1.2.8
 - Repository where this issue was observed: https://github.com/NirmalScaria/le-git-graph/

**Additional context**

I found that the height of graph's line is `57.5px`, where the height of an item of list is `58.39px`. And after I disabled the border of list item (which size is `max(1px, 0,0625rem)`), the list item's height becomes `57.49px` that basiclly solves this problem.

![image](https://github.com/NirmalScaria/le-git-graph/assets/31265413/67ba2ada-02a3-480e-b7ba-6fe583728541)
![image](https://github.com/NirmalScaria/le-git-graph/assets/31265413/caa80d43-4546-4fa5-b55c-73d904c8d590)
![image](https://github.com/NirmalScaria/le-git-graph/assets/31265413/f8748b85-4f21-4d98-aef2-65171ac26dd3)
![image](https://github.com/NirmalScaria/le-git-graph/assets/31265413/8ef201e0-8f0d-4489-a4e5-a4b6ebd454dd)

My browser uses 'Medium' font size which rem seems to be `16px`, and uses 'Arial' as default font (if this matters).

**Comment by AishwaryaAgr** [comment]
The issue seems to be fixed now, if now please help me reproduce it. i am getting

**Comment by Eyre-S** [comment]
There is no any misalignment now.

![image](https://github.com/user-attachments/assets/cf5a3cb5-9ab3-4982-b36a-9a3b82a3b2d7)
